analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.88878
title: Carbonedrums
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5
  brandStrength: 0.5
  rhythmicContrast: 0.5
  brandColors:
    - '#0a0519'
    - '#892c47'
    - '#ffe6ff'
    - '#be8676'
    - '#b6b0e7'
  lightness: 0.1875
purpose: []
favicon: null
name: Carbonedrums
typography_spectrum: 1
