name: Carbonedrums
favicon: null
layout_spectrum: 0.75866
typography_spectrum: 0.875
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Carbonedrums
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bcbcbc'
    - '#242424'
    - '#e3e3e3'
    - '#545454'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
