name: Carbonedrums
favicon: null
layout_spectrum: 0.88878
typography_spectrum: 1
title: Carbonedrums
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0519'
    - '#892c47'
    - '#ffe6ff'
    - '#be8676'
    - '#b6b0e7'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
